#!/usr/bin/env zsh

if [ -f ${HOME}/.dotfiles-public/zsh-customizations.zsh ]; then
    source ${HOME}/.dotfiles-public/zsh-customizations.zsh
fi

if [ -d "${SNAPDIR}" ] && [[ ":$PATH:" != *":${SNAPDIR}:"* ]]; then
    PATH="/snap/bin:${PATH}"
fi