#!/usr/bin/env zsh

if [ -f ${HOME}/.dotfiles-public/zsh-customizations.zsh ]; then
    source ${HOME}/.dotfiles-public/zsh-customizations.zsh
fi

SNAPDIR="/snap/bin"
if [ -d "${SNAPDIR}" ] && [[ ":$PATH:" != *":${SNAPDIR}:"* ]]; then
    PATH="${SNAPDIR}:${PATH}"
fi